### PR TITLE
feat: tsfresh features @mathieu

### PR DESCRIPTION
**Pull request by MathieuCayssol**

### CODE REVIEW

**Review by topher-lo — COMMENTED** [review]
Will revisit after unit tests

**Comment by vienneraphael** [comment]
@MathieuCayssol While reviewing the code, in the `benford_correlation` function, I found that using this:
```python
df.select(
    pl.col("value").cast(pl.Utf8).str.slice(0,1).cast(pl.UInt8),
)
``` 
instead of 
```python
X = (
        (x / (10 ** x.abs().log10().floor()))
        .abs()
        .floor()
    )
``` 
is a bit faster (tried up to 10M values). On top of that i find it more straightforward (slice the first digit from the string).
From my benchmarks, it is approximately ***2.6x faster*** than using log and floors.
for 100M random samples: ***4.28s VS 1.66s***
@topher-lo what's your take on this?

**Comment by topher-lo** [comment]
@vienneraphael that's a super interesting insight. If it passes the tests, let go for it.

**Comment by abstractqqq** [comment]
@vienneraphael  @MathieuCayssol 

I think we need to rebenchmark. See here. https://github.com/neocortexdb/functime/issues/41 

There are 2 potential issues here
1. In your string example, you are not left stripping
2. In your math example, we could have done (x.abs() / (10 ** x.abs().log10().floor())), which will trigger CSE on x.abs(). We should also try not to floor outside. Intuitively, value counts with ints should be much faster than value counts with floats.

I will spend some time later on this. It will be great if you can take a closer look and consider the comments here.

**Comment by vienneraphael** [comment]
@abstractqqq In the meantime, we added left stripping because we realized some edge cases were not right at this time:
- negative numbers
- Numbers starting with zeros
Now that it's all fair and square, it seems like both methods are somehow tied. See my benchmark here in the comments: #41 

Note: my benchmarks are done in polars 0.18. I'm adding them with 0.19.2 just now.

**Pull request merged**
